trigger:
  branches:
    include:
    - dev
    - feature-to-dev/*
jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.12.1'
          checkLatest: true
        displayName: 'installing Node.js 18.12.1'
      - script: 
          npx lint-staged
        displayName: 'npx lint'
      - script: 
          npm install
        displayName: 'npm install'
      - script: 
          npm run build:development
        displayName: 'npm build'
      - script: |
          cd $(Build.SourcesDirectory)
          ls -al
        displayName: 'checking directory'
      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: 'time_tracking'
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: |
            build/**
          targetFolder: '/var/www/html/time-tracking-front-dev'
          readyTimeout: '20000'
        displayName: 'copying files'        