variables:
- group: DOKKU_DEV_FRONT_VARIABLES
- name: DOKKU_PROJECT_NAME
  value: time-tracking-frontend

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(SSH_KNOWN_HOSTS_ENTRY)
    sshPublicKey: $(SSH_PUBLIC_KEY)
    sshKeySecureFile: $(SSH_PRIVATE_KEY_FILENAME)
- script: |
    git remote add dokku dokku@$DOKKU_SERVER:$DOKKU_PROJECT_NAME
    git remote -v
    ls -la /home/vsts/work/_temp/
    git push dokku dev:master --force
  displayName: 'Deploy to Dokku'
