version: '3.7'

networks:
  time_tracking_main:
    driver: bridge

services:
  react:
    networks:
      - time_tracking_main
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.development
    image: time_tracking_development_react_local
    volumes:
      - .:/app
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    command: ["/bin/sh", "/app/scripts/run-local.sh"]
