FROM node:18-alpine

WORKDIR /app

ARG MAX_OLD_SPACE_SIZE=8192
ENV NODE_OPTIONS=--max-old-space-size=$(MAX_OLD_SPACE_SIZE)

COPY package.json .

COPY .npmrc .

RUN npm install

COPY . .

# add `/app/node_modules/.bin` to $PATH

ENV PATH /app/node_modules/.bin:$PATH

RUN chmod -R +x scripts

CMD [ "/app/scripts/run-local.sh" ]
