FROM node:18-alpine

WORKDIR /app

COPY package.json .

COPY .npmrc .

RUN export NODE_OPTIONS=--max_old_space_size=6144

RUN npm install

COPY . .

# add `/app/node_modules/.bin` to $PATH

ENV PATH /app/node_modules/.bin:$PATH

RUN chmod -R +x scripts

CMD [ "/app/scripts/run-local.sh" ]
