export const permissions = {
  auth_delete_group: 'auth.delete_group',
  sites_change_site: 'sites.change_site',
  django_celery_beat_add_crontabschedule:
    'django_celery_beat.add_crontabschedule',
  sessions_change_session: 'sessions.change_session',
  users_change_commenthistory: 'users.change_commenthistory',
  contenttypes_change_contenttype: 'contenttypes.change_contenttype',
  vilmate_comments_view_vilmatecomment: 'vilmate_comments.view_vilmatecomment',
  work_items_view_workitem: 'work_items.view_workitem',
  auth_change_group: 'auth.change_group',
  vilmate_comments_change_vilmatecomment:
    'vilmate_comments.change_vilmatecomment',
  users_delete_expensehistory: 'users.delete_expensehistory',
  contenttypes_add_contenttype: 'contenttypes.add_contenttype',
  work_items_view_processeduserflag: 'work_items.view_processeduserflag',
  work_items_add_comment: 'work_items.add_comment',
  users_change_processeduserflag: 'users.change_processeduserflag',
  history_add_history: 'history.add_history',
  money_change_currency: 'money.change_currency',
  users_change_socialaccount: 'users.change_socialaccount',
  sites_delete_site: 'sites.delete_site',
  django_celery_beat_delete_intervalschedule:
    'django_celery_beat.delete_intervalschedule',
  users_view_expensehistory: 'users.view_expensehistory',
  django_celery_beat_change_periodictask:
    'django_celery_beat.change_periodictask',
  projects_change_rate: 'projects.change_rate',
  users_delete_exchangerate: 'users.delete_exchangerate',
  users_add_processeduserflag: 'users.add_processeduserflag',
  history_view_history: 'history.view_history',
  vilmate_comments_add_vilmatecomment: 'vilmate_comments.add_vilmatecomment',
  history_add_historyfield: 'history.add_historyfield',
  history_change_historyfield: 'history.change_historyfield',
  users_view_socialaccount: 'users.view_socialaccount',
  projects_view_developerprojectchangestatus:
    'projects.view_developerprojectchangestatus',
  projects_view_developerproject: 'projects.view_developerproject',
  django_celery_beat_delete_periodictasks:
    'django_celery_beat.delete_periodictasks',
  work_items_add_processeduserflag: 'work_items.add_processeduserflag',
  users_view_exchangerate: 'users.view_exchangerate',
  projects_add_project: 'projects.add_project',
  contenttypes_view_contenttype: 'contenttypes.view_contenttype',
  django_celery_beat_view_intervalschedule:
    'django_celery_beat.view_intervalschedule',
  history_view_historyfield: 'history.view_historyfield',
  gsheets_change_accesscredentials: 'gsheets.change_accesscredentials',
  users_view_token: 'users.view_token',
  django_celery_beat_view_clockedschedule:
    'django_celery_beat.view_clockedschedule',
  auth_add_permission: 'auth.add_permission',
  users_change_salary: 'users.change_salary',
  django_celery_beat_delete_solarschedule:
    'django_celery_beat.delete_solarschedule',
  admin_delete_logentry: 'admin.delete_logentry',
  work_items_change_comment: 'work_items.change_comment',
  projects_delete_project: 'projects.delete_project',
  django_celery_beat_add_periodictask: 'django_celery_beat.add_periodictask',
  work_items_delete_workitem: 'work_items.delete_workitem',
  users_change_user: 'users.change_user',
  work_items_view_workitemhistory: 'work_items.view_workitemhistory',
  money_add_currency: 'money.add_currency',
  users_add_expensehistory: 'users.add_expensehistory',
  projects_add_workitem: 'projects.add_workitem',
  users_add_user: 'users.add_user',
  django_celery_beat_view_solarschedule:
    'django_celery_beat.view_solarschedule',
  gsheets_add_accesscredentials: 'gsheets.add_accesscredentials',
  auth_delete_permission: 'auth.delete_permission',
  auth_add_group: 'auth.add_group',
  gsheets_view_accesscredentials: 'gsheets.view_accesscredentials',
  users_view_commenthistory: 'users.view_commenthistory',
  users_add_exchangerate: 'users.add_exchangerate',
  history_delete_historyfield: 'history.delete_historyfield',
  users_add_token: 'users.add_token',
  users_change_token: 'users.change_token',
  sessions_delete_session: 'sessions.delete_session',
  projects_add_developerproject: 'projects.add_developerproject',
  auth_view_group: 'auth.view_group',
  projects_view_project: 'projects.view_project',
  admin_change_logentry: 'admin.change_logentry',
  users_delete_salary: 'users.delete_salary',
  django_celery_beat_change_intervalschedule:
    'django_celery_beat.change_intervalschedule',
  django_celery_beat_view_periodictask: 'django_celery_beat.view_periodictask',
  work_items_add_workitem: 'work_items.add_workitem',
  admin_add_logentry: 'admin.add_logentry',
  admin_view_logentry: 'admin.view_logentry',
  users_change_exchangerate: 'users.change_exchangerate',
  django_celery_beat_add_intervalschedule:
    'django_celery_beat.add_intervalschedule',
  users_delete_processeduserflag: 'users.delete_processeduserflag',
  projects_delete_developerproject: 'projects.delete_developerproject',
  sites_add_site: 'sites.add_site',
  sites_view_site: 'sites.view_site',
  projects_delete_workitem: 'projects.delete_workitem',
  users_add_salary: 'users.add_salary',
  sessions_add_session: 'sessions.add_session',
  money_delete_currency: 'money.delete_currency',
  django_celery_beat_add_solarschedule: 'django_celery_beat.add_solarschedule',
  work_items_delete_processeduserflag: 'work_items.delete_processeduserflag',
  history_change_history: 'history.change_history',
  work_items_change_processeduserflag: 'work_items.change_processeduserflag',
  projects_add_rate: 'projects.add_rate',
  django_celery_beat_delete_periodictask:
    'django_celery_beat.delete_periodictask',
  users_view_user: 'users.view_user',
  django_celery_beat_change_periodictasks:
    'django_celery_beat.change_periodictasks',
  gsheets_delete_accesscredentials: 'gsheets.delete_accesscredentials',
  projects_view_workitem: 'projects.view_workitem',
  vilmate_comments_delete_vilmatecomment:
    'vilmate_comments.delete_vilmatecomment',
  projects_delete_rate: 'projects.delete_rate',
  users_change_expensehistory: 'users.change_expensehistory',
  money_view_currency: 'money.view_currency',
  django_celery_beat_delete_crontabschedule:
    'django_celery_beat.delete_crontabschedule',
  django_celery_beat_change_solarschedule:
    'django_celery_beat.change_solarschedule',
  users_delete_token: 'users.delete_token',
  projects_view_rate: 'projects.view_rate',
  projects_delete_developerprojectchangestatus:
    'projects.delete_developerprojectchangestatus',
  django_celery_beat_add_periodictasks: 'django_celery_beat.add_periodictasks',
  projects_change_project: 'projects.change_project',
  users_add_commenthistory: 'users.add_commenthistory',
  django_celery_beat_view_periodictasks:
    'django_celery_beat.view_periodictasks',
  projects_change_developerproject: 'projects.change_developerproject',
  django_celery_beat_change_crontabschedule:
    'django_celery_beat.change_crontabschedule',
  django_celery_beat_view_crontabschedule:
    'django_celery_beat.view_crontabschedule',
  django_celery_beat_change_clockedschedule:
    'django_celery_beat.change_clockedschedule',
  work_items_add_workitemhistory: 'work_items.add_workitemhistory',
  work_items_delete_workitemhistory: 'work_items.delete_workitemhistory',
  auth_view_permission: 'auth.view_permission',
  users_delete_user: 'users.delete_user',
  users_add_socialaccount: 'users.add_socialaccount',
  contenttypes_delete_contenttype: 'contenttypes.delete_contenttype',
  work_items_view_comment: 'work_items.view_comment',
  users_view_processeduserflag: 'users.view_processeduserflag',
  auth_change_permission: 'auth.change_permission',
  users_delete_socialaccount: 'users.delete_socialaccount',
  django_celery_beat_add_clockedschedule:
    'django_celery_beat.add_clockedschedule',
  django_celery_beat_delete_clockedschedule:
    'django_celery_beat.delete_clockedschedule',
  work_items_change_workitemhistory: 'work_items.change_workitemhistory',
  projects_add_developerprojectchangestatus:
    'projects.add_developerprojectchangestatus',
  projects_change_developerprojectchangestatus:
    'projects.change_developerprojectchangestatus',
  projects_change_workitem: 'projects.change_workitem',
  work_items_delete_comment: 'work_items.delete_comment',
  history_delete_history: 'history.delete_history',
  work_items_change_workitem: 'work_items.change_workitem',
  users_view_salary: 'users.view_salary',
  users_delete_commenthistory: 'users.delete_commenthistory',
  sessions_view_session: 'sessions.view_session',
}
