export const VILMATES_PAGE_GET_USERS_LIST_REQUEST =
  'VILMATES_PAGE_GET_USERS_LIST_REQUEST'
export const VILMATES_PAGE_GET_USERS_LIST_SUCCESS =
  'VILMATES_PAGE_GET_USERS_LIST_SUCCESS'
export const VILMATES_PAGE_GET_USERS_LIST_ERROR =
  'VILMATES_PAGE_GET_USERS_LIST_ERROR'
