export const VILMATES_PAGE_GET_USERS_LIST_REQUEST =
  'VILMATES_PAGE_GET_USERS_LIST_REQUEST'
export const VILMATES_PAGE_GET_USERS_LIST_SUCCESS =
  'VILMATES_PAGE_GET_USERS_LIST_SUCCESS'
export const VILMATES_PAGE_GET_USERS_LIST_ERROR =
  'VILMATES_PAGE_GET_USERS_LIST_ERROR'

export const VILMATES_PAGE_SELECT_USER_REQUEST =
  'VILMATES_PAGE_SELECT_USER_REQUEST'
export const VILMATES_PAGE_SELECT_USER_SUCCESS =
  'VILMATES_PAGE_SELECT_USER_SUCCESS'
export const VILMATES_PAGE_SELECT_USER_ERROR = 'VILMATES_PAGE_SELECT_USER_ERROR'

export const VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_REQUEST =
  'VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_REQUEST'
export const VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_SUCCESS =
  'VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_SUCCESS'
export const VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_ERROR =
  'VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_ERROR'

export const VILMATE_PAGE_CHANGE_USER_ON_PROJECT_REQUEST =
  'VILMATE_PAGE_CHANGE_USER_ON_PROJECT_REQUEST'
export const VILMATE_PAGE_CHANGE_USER_ON_PROJECT_SUCCESS =
  'VILMATE_PAGE_CHANGE_USER_ON_PROJECT_SUCCESS'

export const VILMATE_PAGE_ADD_DEVELOPER_PROJECT_REQUEST =
  'VILMATE_PAGE_ADD_DEVELOPER_PROJECT_REQUEST'
export const VILMATE_PAGE_ADD_DEVELOPER_PROJECT_SUCCESS =
  'VILMATE_PAGE_ADD_DEVELOPER_PROJECT_SUCCESS'

export const VILMATES_PAGE_GET_COMMENTS_REQUEST =
  'VILMATES_PAGE_GET_COMMENTS_REQUEST'
export const VILMATES_PAGE_GET_COMMENTS_SUCCESS =
  'VILMATES_PAGE_GET_COMMENTS_SUCCESS'
export const VILMATES_PAGE_GET_COMMENTS_ERROR =
  'VILMATES_PAGE_GET_COMMENTS_ERROR'

export const VILMATES_PAGE_POST_COMMENT_REQUEST =
  'VILMATES_PAGE_POST_COMMENT_REQUEST'
export const VILMATES_PAGE_POST_COMMENT_SUCCESS =
  'VILMATES_PAGE_POST_COMMENT_SUCCESS'
export const VILMATES_PAGE_POST_COMMENT_ERROR =
  'VILMATES_PAGE_POST_COMMENT_ERROR'

export const VILMATES_SINGLE_PAGE_UPDATE_USER_PERSONAL_INFORMATION_REQUEST =
  'VILMATES_SINGLE_PAGE_UPDATE_USER_PERSONAL_INFORMATION_REQUEST'

export const VILMATES_PAGE_DELETE_COMMENT_REQUEST =
  'VILMATES_PAGE_DELETE_COMMENT_REQUEST'
export const VILMATES_PAGE_DELETE_COMMENT_SUCCESS =
  'VILMATES_PAGE_DELETE_COMMENT_SUCCESS'
export const VILMATES_PAGE_DELETE_COMMENT_ERROR =
  'VILMATES_PAGE_DELETE_COMMENT_ERROR'

export const OCCUPATION = {
  FULL_TIME: 'Salary',
  PART_TIME: 'Hourly payroll',
}
