export const VILMATES_PAGE_GET_USERS_LIST_REQUEST =
  'VILMATES_PAGE_GET_USERS_LIST_REQUEST'
export const VILMATES_PAGE_GET_USERS_LIST_SUCCESS =
  'VILMATES_PAGE_GET_USERS_LIST_SUCCESS'
export const VILMATES_PAGE_GET_USERS_LIST_ERROR =
  'VILMATES_PAGE_GET_USERS_LIST_ERROR'

export const VILMATES_PAGE_SELECT_USER_REQUEST =
  'VILMATES_PAGE_SELECT_USER_REQUEST'
export const VILMATES_PAGE_SELECT_USER_SUCCESS =
  'VILMATES_PAGE_SELECT_USER_SUCCESS'
export const VILMATES_PAGE_SELECT_USER_ERROR = 'VILMATES_PAGE_SELECT_USER_ERROR'

export const VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_REQUEST =
  'VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_REQUEST'
export const VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_SUCCESS =
  'VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_SUCCESS'
export const VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_ERROR =
  'VILMATES_PAGE_GET_DEVELOPER_PROJECTS_LIST_ERROR'

export const OCCUPATION = {
  FULL_TIME: 'Salary',
  PART_TIME: 'Hourly',
}
